name: flutterfire_samples
description: Firebase + Flutter sample apps with code snippets, supported by comprehensive articles for each implementation.

publish_to: "none"
version: 2.6.1+11

environment:
  sdk: ">=3.0.0 <3.30.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  font_awesome_flutter: ^10.7.0
  pin_code_fields: ^8.0.1
  firebase_database: ^11.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: fonts/OpenSans-Bold.ttf
          weight: 600
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 700
