// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCZxRud84nFLDID14T0-0HE16s-yudEQss",
      authDomain: "charge-ride.firebaseapp.com",
      databaseURL: "https://charge-ride-default-rtdb.firebaseio.com",
      projectId: "charge-ride",
      storageBucket: "charge-ride.appspot.com",
      messagingSenderId: "409578109650",
      appId: "1:409578109650:web:a2c053368eed4d0dafcb0b",
      measurementId: "G-M26DPH42L5"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZxRud84nFLDID14T0-0HE16s-yudEQss',
    appId: '1:409578109650:android:93356456eb584790afcb0b',
    messagingSenderId: '409578109650',
    projectId: 'charge-ride',
    storageBucket: 'charge-ride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ8CIHpQyX7F3gJH_9ISofTLdXz6Ds7QQ',
    appId: '1:409578109650:ios:2380e37a9e226affafcb0b',
    messagingSenderId: '409578109650',
    projectId: 'charge-ride',
    storageBucket: 'charge-ride.appspot.com',
    androidClientId: '409578109650-kshqkptb3qheoaro8qqmlvias60ojttb.apps.googleusercontent.com',
    iosClientId: '409578109650-uu3rftco28oc052234vh7a5qpn0jovl2.apps.googleusercontent.com',
    iosBundleId: 'com.test.chargeride',
  );
}
